### PR TITLE
feat: add update_in_normal

### PR DESCRIPTION
**Pull request by 0xAdk**
Updates the preview when text changes while in normal mode.

probably should have a better name, but I couldn't think of a good one :sweat_smile:

### CODE REVIEW

**Comment by toppair** [comment]
Hi, can you provide me with some reproducible scenario in which setting that autocmd would be necessary? Things like paste and substitute seem to be covered by currently used autocmds. Unless of course you set `update_in_insert = false` but that kind of implies that you want to update on buffer write only. Don't want to needlessly set too much autocmds or introduce too much options. I probably am missing something so clarification is required :)

**Comment by 0xAdk** [comment]
> Hi, can you provide me with some reproducible scenario in which setting that autocmd would be necessary?

just from some basic testing
* deleting text with `d`
* surrounding text with nvim-surround
* undo and redo

**Comment by toppair** [comment]
Okay, I removed [this plugin](https://github.com/antoinemadec/FixCursorHold.nvim) and have the same problem now, sorry for the fuss.

Do you think that maybe we could simply set this autocmd inside update_in_insert check, without introducing new option? Cause as i said earlier `update_in_insert = false` basically means 'update on write only'. I don't think anyone expects updates on changes in normal mode when they set `update_in_insert = false`.

**Comment by 0xAdk** [comment]
> Do you think that maybe we could simply set this autocmd inside update_in_insert check

that's fine.. but it's a little odd naming wise. I'd expect that `update_in_insert` to select if it will update during insert, not normal.

I initially was going to replace `update_in_insert` with `update_on_change`, but that would be a breaking change...

If you do want to do that I feel like it's common practice on a breaking change to keep `update_in_insert` as a undocumented alias with a warning on startup that the user should change it to `update_on_change`.

**Comment by toppair** [comment]
> If you do want to do that I feel like it's common practice on a breaking change to keep update_in_insert as a undocumented alias with a warning on startup that the user should change it to update_on_change.

I'm okay with that.

**Comment by 0xAdk** [comment]
There you go. If you give setup `update_in_insert` it'll emit a warning while still working as intended. This also ends up making the code a bit cleaner since `CursorMoved` and `TextChanged` now get grouped with their insert counter parts.

**Comment by toppair** [comment]
Thanks!

**Pull request merged**
